word = list(input())
word.sort()
word2 = str(word)
word2 = word2.replace(" ", "")
word2 = word2.replace("[", "")
word2 = word2.replace("]", "")
word2 = word2.replace("'", "")
word2 = word2.replace(",", "")
print(word2)